"""Seed du référentiel de sous-jacents.

Repris tel quel du fichier frontend qui tenait cette liste avant qu'elle passe
en base : mêmes tickers, mêmes libellés, mêmes groupes. Un ticker peut figurer
dans deux groupes — BNP Paribas est à la fois une valeur du CAC et une banque —
et c'est voulu : la table est unique sur le couple (ticker, groupe).

Les devises sont déduites du suffixe de cotation (.PA → EUR, .SW → CHF…) : c'est
une inférence, corrigible depuis l'administration.
"""

# (ticker, libellé, groupe, devise)
UNDERLYINGS_SEED: list[tuple[str, str, str, str]] = [
    ('^STOXX50E', "Euro Stoxx 50", 'Indices Europe', 'EUR'),
    ('^FCHI', "CAC 40", 'Indices Europe', 'EUR'),
    ('^GDAXI', "DAX 40", 'Indices Europe', 'EUR'),
    ('^FTSE', "FTSE 100", 'Indices Europe', 'GBP'),
    ('^IBEX', "IBEX 35", 'Indices Europe', 'EUR'),
    ('^SSMI', "SMI", 'Indices Europe', 'CHF'),
    ('^GSPC', "S&P 500", 'Indices US', 'USD'),
    ('^NDX', "Nasdaq 100", 'Indices US', 'USD'),
    ('^DJI', "Dow Jones", 'Indices US', 'USD'),
    ('^RUT', "Russell 2000", 'Indices US', 'USD'),
    ('^N225', "Nikkei 225", 'Indices Asie', 'JPY'),
    ('^HSI', "Hang Seng", 'Indices Asie', 'HKD'),
    ('000300.SS', "CSI 300", 'Indices Asie', 'CNY'),
    ('MC.PA', "LVMH", 'Actions FR (CAC)', 'EUR'),
    ('TTE.PA', "TotalEnergies", 'Actions FR (CAC)', 'EUR'),
    ('SAN.PA', "Sanofi", 'Actions FR (CAC)', 'EUR'),
    ('BNP.PA', "BNP Paribas", 'Actions FR (CAC)', 'EUR'),
    ('AXA.PA', "AXA", 'Actions FR (CAC)', 'EUR'),
    ('OR.PA', "L'Oréal", 'Actions FR (CAC)', 'EUR'),
    ('AIR.PA', "Airbus", 'Actions FR (CAC)', 'EUR'),
    ('GLE.PA', "Société Générale", 'Actions FR (CAC)', 'EUR'),
    ('STMPA.PA', "STMicroelectronics (Paris)", 'Actions FR (CAC)', 'EUR'),
    ('AAPL', "Apple", 'Actions US', 'USD'),
    ('MSFT', "Microsoft", 'Actions US', 'USD'),
    ('NVDA', "Nvidia", 'Actions US', 'USD'),
    ('AMZN', "Amazon", 'Actions US', 'USD'),
    ('GOOGL', "Alphabet", 'Actions US', 'USD'),
    ('META', "Meta", 'Actions US', 'USD'),
    ('TSLA', "Tesla", 'Actions US', 'USD'),
    ('GLD', "GLD (Or)", 'ETF / Matières premières', 'USD'),
    ('SLV', "SLV (Argent)", 'ETF / Matières premières', 'USD'),
    ('USO', "USO (Pétrole WTI)", 'ETF / Matières premières', 'USD'),
    ('SPY', "SPY (S&P 500 ETF)", 'ETF / Matières premières', 'USD'),
    ('QQQ', "QQQ (Nasdaq ETF)", 'ETF / Matières premières', 'USD'),
    ('EEM', "EEM (Émergents)", 'ETF / Matières premières', 'USD'),
    ('UCG.MI', "UniCredit", 'Actions IT (FTSE MIB)', 'EUR'),
    ('ISP.MI', "Intesa Sanpaolo", 'Actions IT (FTSE MIB)', 'EUR'),
    ('STLAM.MI', "Stellantis (Milan)", 'Actions IT (FTSE MIB)', 'EUR'),
    ('STMMI.MI', "STMicroelectronics (Milan)", 'Actions IT (FTSE MIB)', 'EUR'),
    ('ENI.MI', "Eni", 'Actions IT (FTSE MIB)', 'EUR'),
    ('ENEL.MI', "Enel", 'Actions IT (FTSE MIB)', 'EUR'),
    ('G.MI', "Generali", 'Actions IT (FTSE MIB)', 'EUR'),
    ('RACE.MI', "Ferrari", 'Actions IT (FTSE MIB)', 'EUR'),
    ('BNP.PA', "BNP Paribas", 'Banques', 'EUR'),
    ('SAN.MC', "Banco Santander", 'Banques', 'EUR'),
    ('ISP.MI', "Intesa Sanpaolo", 'Banques', 'EUR'),
    ('UCG.MI', "UniCredit", 'Banques', 'EUR'),
    ('GLE.PA', "Société Générale", 'Banques', 'EUR'),
    ('DBK.DE', "Deutsche Bank", 'Banques', 'EUR'),
    ('UBSG.SW', "UBS", 'Banques', 'CHF'),
    ('JPM', "JPMorgan Chase", 'Banques', 'USD'),
    ('GS', "Goldman Sachs", 'Banques', 'USD'),
    ('MS', "Morgan Stanley", 'Banques', 'USD'),
    ('BAC', "Bank of America", 'Banques', 'USD'),
    ('C', "Citigroup", 'Banques', 'USD'),
    ('MC.PA', "LVMH", 'Luxe', 'EUR'),
    ('OR.PA', "L'Oréal", 'Luxe', 'EUR'),
    ('RMS.PA', "Hermès", 'Luxe', 'EUR'),
    ('KER.PA', "Kering", 'Luxe', 'EUR'),
    ('CFR.SW', "Richemont", 'Luxe', 'CHF'),
    ('RL', "Ralph Lauren", 'Luxe', 'USD'),
    ('TPR', "Tapestry", 'Luxe', 'USD'),
    ('EL', "Estée Lauder", 'Luxe', 'USD'),
    ('CPRI', "Capri Holdings", 'Luxe', 'USD'),
    ('PVH', "PVH Corp", 'Luxe', 'USD'),
]
