// CCR explanations describe the implemented economic calculation, not SA-CCR.
export const ccrHelp = {
  refreshMtm: 'Par défaut, une base CCR compatible est réutilisée : mêmes deals, date, termes, fixings, hypothèses et moteur. Cocher force la préparation des MtM et du marché commun. Autoriser la récupération si les historiques locaux sont insuffisants. Les chocs sont toujours valorisés ; leur modification ne nécessite pas de recalculer la base.',
  sortKey: 'Choisit la colonne utilisée pour classer les contreparties dans le monitor, de la valeur la plus élevée à la plus faible.',
  gross_notional: 'Somme des nominaux des deals du périmètre, sans compensation des positions. Montant dans la devise de calcul.',
  gross_positive_mtm: 'Somme des MtM positifs, avant compensation juridique et collatéral. Un MtM positif représente une créance de notre entité.',
  net_mtm: 'Somme signée des MtM : créances positives et dettes négatives. Ce solde comptable ne constitue pas à lui seul une exposition de crédit compensable.',
  collateral: 'Collatéral reçu moins collatéral posté, après décotes et ajout de l’IM reçue reconnue. La réduction du risque dépend des accords et positions reconnus.',
  collateral_held: 'Collatéral reçu reconnu, après la décote applicable.',
  collateral_posted: 'Collatéral posté, ajusté de la décote : il constitue aussi une créance à récupérer.',
  current_exposure: 'Exposition positive à la date d’arrêté, après compensation autorisée et collatéral reconnu, calculée par ensemble juridique puis agrégée. Aucune compensation entre ensembles distincts.',
  immediate_default_loss: 'Exposition courante × (1 − taux de recouvrement du profil). Estimation conditionnelle si la contrepartie fait défaut à la date d’arrêté, sans pondération par une probabilité de défaut. Ni perte maximale, ni CVA, ni mesure réglementaire. Pour une note émise, la créance admise et le recouvrement effectif peuvent différer du MtM et de cette hypothèse.',
  ee: 'EPE : moyenne dans le temps de l’exposition positive attendue (EE) sur les horizons simulés. À chaque horizon, EE est la moyenne des scénarios.',
  pfe95: 'À chaque horizon, quantile 95 % de l’exposition positive sur les scénarios. Cette carte affiche le maximum de ces quantiles sur les horizons. Il ne s’agit ni d’une probabilité de défaut ni d’une perte certaine.',
  pfe99: 'Maximum, sur les horizons simulés, des quantiles 99 % de l’exposition positive. Plus sensible aux scénarios extrêmes et au nombre de simulations que la PFE 95 %.',
  maximum_pfe: 'Maximum de la PFE 95 % sur les horizons, utilisé pour contrôler les limites PFE.',
  cva: 'Ajustement unilatéral de valeur pour le risque de défaut : exposition attendue, probabilités marginales de défaut et perte en cas de défaut, actualisées. Cette version suppose l’indépendance crédit/marché. Une courbe de crédit et un recouvrement documentés sont nécessaires.',
  ead: 'Exposition au défaut réglementaire. Le moteur SA-CCR n’est pas implémenté ; cette valeur reste indisponible et n’est pas remplacée par la PFE économique.',
  stressed_exposure: 'Exposition courante sous les chocs de marché et de crédit explicitement saisis. Il s’agit d’un scénario, pas d’un modèle joint de défaut.',
  dataScope: 'Production retient les deals réels. Recette UAT retient les deals de test et simule les limites ; elle ne valide aucun booking réel.',
  uatBatchId: 'Restreint la recette à un lot de deals générés. Tous les lots UAT conserve l’ensemble des lots accessibles.',
  cptyId: 'Contrepartie juridique dont les deals et le dossier crédit sont analysés, dans votre entité.',
  asOf: 'Date à laquelle les MtM et les expositions sont évalués. L’historique utilisé s’arrête à cette date ; aucune observation future n’est utilisée.',
  currency: 'Devise des montants et des limites. La conversion FX implicite entre devises n’est pas prise en charge par le CCR actuel.',
  analysisPortfolio: 'Filtre les deals par portefeuille. Un sous-périmètre ne suffit pas à valider une limite globale de contrepartie en production.',
  analysisSet: 'Filtre un ensemble de compensation juridique. Aucun netting n’est accordé simplement parce que deux deals ont la même contrepartie.',
  analysisDeal: 'Analyse un deal du périmètre. Les chiffres du deal seul ne représentent pas nécessairement sa contribution au risque du portefeuille.',
  nOuter: 'Nombre de scénarios de marché communs aux deals. Ils déterminent la distribution des expositions et la précision des quantiles PFE. Plus de scénarios augmente le temps de calcul.',
  nInner: 'Nombre de trajectoires utilisées pour revaloriser le payoff résiduel à chaque horizon et scénario extérieur. Plus de trajectoires réduit le bruit de valorisation mais augmente le coût du calcul.',
  nDates: 'Nombre d’horizons demandés. Le moteur ajoute les observations et paiements nécessaires, sur sa grille hebdomadaire : le nombre effectif peut être supérieur.',
  seed: 'Graine du générateur aléatoire. Des entrées, une version moteur et une graine identiques permettent de reproduire le calcul ; ce n’est pas un paramètre économique.',
  mtmPaths: 'Nombre de trajectoires du Monte-Carlo pour le MtM à la date d’arrêté, distinct des simulations imbriquées utilisées pour les PFE.',
  commonRate: 'Taux annuel commun, en pourcentage, utilisé pour le drift et l’actualisation. Par défaut 3 % à titre provisoire, en attendant les taux du jour ; il remplace les taux et courbes des bookings pour ce calcul.',
  commonMarket: 'Construit des volatilités et corrélations communes sur les rendements historiques ajustés. Pour chaque ticker, q vient du booking de référence ou d’une surcharge. Tous les MtM sont recalculés avant les PFE.',
  allowMarketFetch: 'Autorise le fournisseur configuré à compléter les historiques absents ou périmés. Le stockage local et le cache sont consultés d’abord. Les fixings utilisent le brut, la calibration utilise les clôtures ajustées.',
  marketOverrides: 'Surcharges par ticker, en fractions : sigma 0.20 signifie 20 % de volatilité annuelle, q 0.01 signifie 1 % de rendement de dividende. Sigma plat uniquement en GBM. Une surcharge q remplace la courbe de dividendes.',
  correlations: 'Dépendance entre rendements des facteurs, comprise entre −1 et +1. Les surcharges par paire remplacent les valeurs estimées ; la matrice complète doit rester admissible.',
  priceHistories: 'Clôtures contractuelles non ajustées, par ticker, avec dates croissantes et prix positifs. Elles servent au passé du payoff ; elles ne remplacent pas les historiques ajustés de calibration.',
  spot_pct: 'Choc relatif de spot en pourcentage : −20 signifie une baisse de 20 %.',
  vol_points: 'Choc additif de volatilité en points : +10 fait passer 20 % à 30 %.',
  rate_bp: 'Choc additif de taux en points de base : +100 bp ajoute 1 point de pourcentage.',
  correlation_points: 'Choc additif de corrélation en points : +10 fait passer 0,40 à 0,50. Une matrice non admissible bloque la projection.',
  creditMultiplier: 'Multiplicateur de l’intensité de défaut dans le scénario crédit. ×2 double cette intensité, pas directement les probabilités cumulées de défaut.',
  sigma: 'Volatilité annualisée utilisée par le GBM. En mode marché commun, elle est réalisée sur les rendements historiques, sauf surcharge ; elle n’est pas une volatilité implicite.',
  q: 'Rendement annuel de dividende utilisé dans le drift du sous-jacent. Il s’agit ici d’une hypothèse issue du booking de référence ou d’une surcharge, pas d’un dividende futur garanti.',
  utilisation: 'Exposition mesurée divisée par la limite. 100 % signifie que la limite est atteinte. Sans limite définie, aucun ratio n’est calculé.',
  remaining_capacity: 'Limite moins exposition mesurée. Une capacité négative indique un dépassement.',
  incremental: 'Différence signée entre le portefeuille après ajout du deal et le portefeuille avant. Une valeur négative indique une réduction de la métrique de risque.',
  netting_benefit: 'PFE du deal seul moins son incrément de PFE dans le portefeuille. Ce chiffre peut refléter la diversification et la compensation autorisée.',
  legal_name: 'Dénomination complète de la personne morale qui porte les obligations contractuelles.',
  short_name: 'Libellé court utilisé pour identifier la contrepartie dans les tableaux.',
  lei: 'Legal Entity Identifier : identifiant international de la personne morale.',
  counterparty_type: 'Catégorie de la contrepartie ; ne crée aucun accord juridique ou traitement prudentiel automatique.',
  parent_group: 'Groupe de rattachement informatif. Il ne crée pas de compensation entre ses filiales.',
  internal_rating: 'Notation interne renseignée dans le dossier. Elle ne génère pas automatiquement une courbe de défaut.',
  external_rating: 'Notation externe de référence ; préciser sa provenance dans le dossier.',
  recovery: 'Fraction recouvrée après défaut : 0.40 = 40 %. La perte en cas de défaut (LGD) vaut 1 moins le recouvrement.',
  recovery_source: 'Origine du recouvrement : observation, convention ou hypothèse documentée. Une valeur inconnue bloque la CVA.',
  curve_source: 'Origine documentée de la courbe de probabilités de défaut ou de spreads.',
  pd_measure: 'Mesure des probabilités de défaut : les probabilités historiques ne sont pas assimilées à des probabilités risque-neutre pour une CVA marchande.',
  pd_curve: 'Probabilités cumulées de défaut croissantes par maturité, en années et fractions. Exemple JSON : [[1,0.01],[5,0.05]].',
  spread_curve: 'Spreads annuels par maturité en années, en fractions : 0.01 = 100 bp. Conversion approchée intensité = spread / LGD ; aucun bootstrap CDS.',
  has_isda: 'Indique si l’existence d’un accord ISDA est connue. Sa présence seule ne suffit pas à autoriser le netting.',
  has_csa: 'Indique si une annexe de collatéral CSA est connue. UNKNOWN ne signifie pas Oui.',
  agreement_id: 'Référence métier de l’accord-cadre ISDA.',
  agreement_version: 'Version du document juridique applicable.',
  effective_date: 'Première date à laquelle cette configuration est applicable.',
  governing_law: 'Droit régissant l’accord ; cette information ne remplace pas un avis juridique.',
  status: 'État de la fiche. Seuls les accords et configurations admissibles à la date d’arrêté peuvent être utilisés.',
  legal_opinion_available: 'Existence d’un avis juridique disponible sur l’accord et son opposabilité.',
  close_out_netting_enforceable: 'Opposabilité reconnue de la compensation à la clôture après défaut ; condition nécessaire au netting.',
  cross_product_netting_allowed: 'Autorisation de compenser plusieurs types de produits dans le même ensemble juridique.',
  notes: 'Informations complémentaires et limites d’interprétation du dossier.',
  csa_id: 'Référence de l’annexe de collatéral applicable.',
  master_agreement_id: 'Accord-cadre auquel le netting set est rattaché.',
  bilateral: 'Indique que les transferts de marge peuvent avoir lieu dans les deux sens.',
  collateralised: 'Indique que l’ensemble est couvert par un dispositif de collatéral.',
  vm_required: 'La marge de variation couvre les variations de valeur de marché selon le CSA.',
  vm_frequency_days: 'Fréquence des appels de marge, en jours ouvrés selon le calendrier de la devise.',
  threshold_counterparty: 'Seuil d’exposition au-delà duquel la contrepartie doit apporter de la marge.',
  threshold_our_side: 'Seuil au-delà duquel notre entité doit apporter de la marge dans un CSA bilatéral.',
  mta: 'Minimum Transfer Amount : aucun transfert de marge inférieur à ce montant n’est déclenché.',
  independent_amount: 'Montant indépendant ajouté au besoin de marge selon la convention contractuelle.',
  im_required: 'Indique si une marge initiale est requise pour couvrir les variations durant la période de liquidation.',
  im_model: 'Cette version prend en charge une IM fixe ; aucun modèle SIMM n’est calculé.',
  im_amount: 'Montant contractuel de l’IM. Il ne remplace pas une position effectivement reçue et reconnue.',
  segregated: 'Indique si l’IM est détenue séparément des actifs propres du bénéficiaire.',
  im_recognised: 'Autorise la prise en compte de l’IM effectivement reçue et juridiquement reconnue.',
  base_currency: 'Devise des seuils, marges et conventions calendaires du CSA.',
  eligible_collateral: 'Types d’actifs acceptables selon le contrat. Saisir un tableau JSON, par exemple ["CASH"].',
  collateral_haircut: 'Décote de prudence, en fraction : 0.05 = 5 %. Elle réduit la valeur reconnue du collatéral reçu.',
  settlement_lag_days: 'Délai entre appel de marge et règlement effectif, en jours ouvrés.',
  mpor_days: 'Margin Period of Risk : période pendant laquelle les nouveaux appels de marge ne sont pas supposés disponibles pour couvrir le risque.',
  active: 'Active ou désactive l’utilisation de cette fiche.',
  netting_set_id: 'Ensemble de deals pouvant être compensés sous un accord juridique opposable, dans une même devise.',
  product_scope: 'Types de produits explicitement couverts par l’accord. Un produit absent du périmètre ne bénéficie pas du netting.',
  our_legal_entity: 'Personne morale de notre côté signataire de l’accord.',
  counterparty_legal_entity: 'Personne morale contrepartie signataire de l’accord.',
  enforceable_netting: 'Reconnaissance explicite de la compensation pour ce netting set.',
  metric: 'Mesure à comparer à la limite : nominal, exposition courante, PFE, CVA ou autre mesure disponible.',
  amount: 'Montant de la limite, dans sa devise. Une limite absente n’est ni zéro ni une autorisation sans restriction.',
  warning_threshold: 'Fraction de la limite à partir de laquelle une alerte est émise : 0.80 = 80 %.',
  hard_threshold: 'Fraction de la limite correspondant au seuil dur : 1 = 100 %.',
  action: 'Politique appliquée lors du contrôle : avertissement, approbation requise ou blocage selon la configuration. Une demande de dérogation seule ne lève pas un blocage.',
  expiry_date: 'Dernière date de validité de la configuration.',
  as_of_date: 'Date à laquelle la position ou l’information enregistrée est valable.',
  collateral_type: 'Nature de l’actif fourni en garantie, à rapprocher de l’éligibilité du CSA.',
  held: 'Montant de marge de variation effectivement reçu, avant décote.',
  posted: 'Montant de marge de variation effectivement posté, avant ajustement de décote.',
  im_held: 'Marge initiale effectivement reçue, distincte de la marge de variation.',
  recognised: 'Reconnaissance juridique de la position de collatéral pour ce calcul.',
  source: 'Origine et justification de la donnée saisie, conservées pour audit.',
  limit_id: 'Limite existante concernée par la demande de dérogation.',
  requested_by: 'Identifiant de l’utilisateur à l’origine de la demande.',
  approved_by: 'Identifiant de l’approbateur. Le circuit de dérogation à quatre yeux n’est pas activé dans cette version.',
  reason: 'Justification explicite de la modification ou de la demande, enregistrée dans l’audit.',
  previous_limit: 'Montant de la limite avant la modification demandée.',
  temporary_limit: 'Montant temporaire demandé. Son enregistrement seul ne modifie pas la limite autorisée.',
}
