export const workshopHelp = {
  manage:'Réinitialiser la vue enlève les filtres et ferme la preuve sélectionnée sans modifier les données. Recommencer remplace cet essai par une campagne vierge aux mêmes paramètres ; les IA doivent recréer leurs comptes et contrats. Supprimer retire cet essai de la liste. Les deux dernières commandes exigent des IA arrêtées et une confirmation ; les anciens fichiers restent dans une sauvegarde locale.',
  page:'Cette page observe des IA qui utilisent des installations Structura isolées. Elle sert à relever les erreurs de l’application et de ses utilisateurs. Les résultats commerciaux ne constituent pas une validation de toutes les fonctions.',
  campaigns:'Une campagne est une partie indépendante, avec ses acteurs, comptes, contrats, messages, opérations et signalements. Sélectionner une campagne consulte son historique ; cela ne démarre pas ses IA.',
  name:'Nom libre pour retrouver cette campagne. Il ne modifie pas les instructions ou décisions des agents.',
  model:'Modèle local exécuté par Ollama pour prendre les décisions. Chaque acteur a son contexte propre. Un modèle plus grand peut être plus lent ; une réponse IA peut être erronée.',
  start:'Première date du jeu, utilisée pour les prix et les événements. Le marché est synthétique : choisir une date ancienne ne charge pas les cours historiques réels.',
  months:'Nombre de mois virtuels à parcourir. Un mois avance après la clôture du dossier commercial et les revues de books nécessaires. La durée du jeu est distincte de la durée réelle du calcul.',
  ticket:'Nominal de chaque besoin client simulé, en euros. Ce paramètre ne représente ni un prix de note ni un budget de calcul.',
  target:'Objectif commercial d’Hector pour la campagne entière. Il motive l’agent mais ne force aucun trade et ne conditionne pas la réussite des tests.',
  decisions:'Budget maximal de décisions des acteurs commerciaux. Une décision peut être un message, une attente ou une opération. Les appels supplémentaires d’Achille peuvent augmenter le nombre d’appels au modèle.',
  timeout:'Délai maximal pour recevoir une réponse du modèle IA, en secondes. Ce n’est pas la durée de la campagne ni un délai global pour tous les calculs de Structura.',
  seed:'Nombre qui fixe le marché synthétique et le tirage des prérequis contractuels. La même graine reproduit ces données ; elle ne garantit pas des décisions IA identiques.',
  contracts:'Scénario de documentation : BNP/SG complets et CA incomplet, toutes les banques documentées, ou prérequis tirés au sort. Les agents enregistrent ensuite les relations dans Structura. Les notes et les accords OTC ISDA/CSA sont distincts.',
  sg:'Ajoute Société Générale aux banques de cette campagne. Si elle est exclue, les compteurs et réponses attendues sont calculés sur les banques présentes.',
  coaching:'Achille analyse les erreurs et les explications commerciales, puis conseille les agents. Il ne corrige pas le code de Structura et ses conseils restent à vérifier.',
  controls:'Démarrer crée ou reconnecte les installations privées. Pause attend la fin de l’action en cours. Arrêter ferme ces installations et conserve les preuves. Une campagne terminée reste consultable.',
  export:'Télécharge le journal complet de la campagne : actions, conversations, signalements et résultats. Les secrets de connexion sont exclus. Ce fichier permet d’analyser les problèmes hors de l’interface.',
  overview:'Vue de supervision : activité courante, temps du jeu, résultats, étapes atteintes et dernières actions. Les compteurs décrivent les faits conservés pour la campagne sélectionnée.',
  messages:'Messages internes entre les agents : besoins, négociations et informations client. Un message ne crée pas à lui seul un prix dans le Pricer ou un deal dans un book.',
  actions:'Chaque ligne est une décision exécutée avec son résultat. Cliquer ouvre sa preuve : capture disponible, appels HTTP, référence de deal et données détaillées. Écran et API sont distingués.',
  books:'Rapprochement des livres des parties : vente banque / achat Hector, puis vente Hector / achat client. Le risque du porteur sur l’émetteur d’une note est distinct du calcul CCR sur un OTC hypothétique.',
  incidents:'Registre des problèmes de la campagne. Il rassemble les signalements IA, erreurs observées et améliorations. Un problème signalé n’est pas automatiquement un bug Structura confirmé ; sa preuve doit être examinée.',
  now:'Ce que le contrôleur publie actuellement : préparation, réflexion IA, exécution, pause ou arrêt. Pendant la réflexion aucune nouvelle opération métier n’est encore exécutée. Un état ancien sans contrôleur actif est signalé.',
  clock:'Date économique du scénario. Le temps virtuel reste suspendu pendant les décisions et calculs. « 0 / 1 mois » signifie que le premier mois n’est pas clôturé, même si des actions ont déjà été réalisées.',
  volume:'Somme des ventes clients dont les quatre écritures ont été rapprochées. Une quote ou un booking partiel ne compte pas. Ainsi un dossier avec 1 / 4 écritures peut afficher 0 €.',
  matched:'Nombre de dossiers avec quatre écritures cohérentes entre les parties : banque SELL, Hector BUY, Hector SELL, client BUY. Ce compteur ne représente pas le nombre total de deals créés.',
  issues:'Nombre de signalements conservés, y compris les répétitions et problèmes du pilote. Il ne représente pas un nombre de bugs Structura confirmés. Cliquez pour ouvrir les fiches à examiner.',
  usage:'Actions terminées ayant une preuve d’utilisation. « Écran » correspond à une action navigateur ; « API » à des appels natifs. Une même inscription peut compter dans les deux. Les messages et attentes sont distingués.',
  failures:'Nombre d’actions marquées en échec. Cela peut venir d’une erreur IA, d’un contrôle métier de Structura ou d’un défaut technique. Plusieurs échecs peuvent provenir du même problème.',
  workflow:'États déduits des données enregistrées, pour le dossier choisi. Vert : réalisé ; bleu : première étape encore incomplète ; orange : documentation manquante ou écart ; tiret : sans objet après refus. Ce schéma ne prouve pas que les opérations ont eu lieu dans le bon ordre.',
  accounts:'Nombre d’acteurs commerciaux ayant créé ou reconnecté leur compte pendant la campagne. Ce fait reste enregistré quand leurs installations sont fermées. Achille n’a pas de book commercial.',
  relationships:'Relations enregistrées dans chaque book, dans les deux sens. « 6 / 6 » signifie six relations saisies, pas six relations éligibles : les relations PENDING restent orange. Une banque mal documentée peut être refusée alors que les autres traitent.',
  request:'Besoin reçu du client, avec son nominal et sa structure. CASE-001 est une référence de dossier de recette, pas une référence de deal déjà booké.',
  rfq:'Réponses des banques présentes : une cotation ou un refus explicite compte comme réponse. « 1 / 2 réponses · 1 prix » signifie qu’une banque a coté et que l’autre n’a pas encore clôturé sa réponse.',
  agreements:'Accord client sur l’offre, puis cotation bancaire retenue par Hector. Des accords enregistrés ne prouvent ni le règlement ni le booking complet.',
  booking:'Nombre d’écritures reçues sur les quatre attendues. « 1 / 4 » indique une opération partielle : chercher les refus des autres parties dans Actions et preuves et dans le registre des problèmes.',
  lifecycle:'Revues des books à la date du jeu, règlements et événements des produits. Cette étape porte sur l’ensemble des deals existants, pas uniquement sur le dernier dossier.',
  actors:'Chaque acteur a son propre compte, ses décisions et son book. Cliquer son nom filtre les actions et conversations. « Voir la dernière preuve » ouvre le résultat de sa dernière action hors attente.',
  coverage:'Fonctions effectivement exercées par cette campagne. Une fonction non exercée reste à tester. Les codes bruts sont conservés dans l’export et les détails de preuve.',
  http:'Réponse de l’installation Structura : 200/201 = appel accepté ; 400/422 = données ou contrôle métier refusés ; 401/403 = authentification ou droits ; 404 = route ou objet introuvable ; 500 = erreur serveur à diagnostiquer. Une réponse HTTP ne valide pas à elle seule tout le parcours.',
}

export const stepHelp = {Comptes:'accounts',Contrats:'relationships','Besoin client':'request','Appel d’offres':'rfq',Accords:'agreements',Booking:'booking','Suivi de vie':'lifecycle'}
