<script setup>
import { ref, onMounted } from 'vue'
import { apiFetch, apiErrorMessage } from '../utils/api'
import BackLink from '../components/ui/BackLink.vue'
const relations=ref([]), executions=ref([]), counterparties=ref([]), positions=ref(null), error=ref(''), busy=ref(false), editing=ref(null)
const empty=()=>({counterparty_id:null,reference:'',status:'PENDING',effective_date:new Date().toISOString().slice(0,10),expiry_date:null,currency:'EUR',note_distribution_allowed:true,otc_allowed:false,documentation_reference:'',gross_notional_limit:100000000,master_agreement_id:null,csa_id:null,csa_required:false,settlement:'DVP',notes:''})
const form=ref(empty()), proofs=ref({})
async function api(path,options={}) { const res=await apiFetch('/api'+path,{...options,headers:options.body?{'Content-Type':'application/json'}:{}}); const body=await res.json().catch(()=>({})); if(!res.ok) throw new Error(apiErrorMessage(body)); return body }
async function load() { try { [relations.value,executions.value,counterparties.value,positions.value]=await Promise.all([api('/trading/relationships'),api('/trading/executions'),api('/deals/counterparties'),api('/trading/positions')]); error.value='' } catch(e){error.value=e.message} }
function edit(row){ editing.value=row.id; form.value={...row}; delete form.value.id; delete form.value.version }
function reset(){editing.value=null;form.value=empty()}
async function save(){ busy.value=true; try { const row=relations.value.find(r=>r.id===editing.value); const data={...form.value,expiry_date:form.value.expiry_date||null}; if(row) data.expected_version=row.version; await api('/trading/relationships'+(row?'/'+row.id:''),{method:row?'PUT':'POST',body:JSON.stringify(data)}); reset();await load() } catch(e){error.value=e.message} finally{busy.value=false} }
async function settle(row){busy.value=true;try{await api(`/trading/executions/${row.id}/settle`,{method:'POST',body:JSON.stringify({reference:proofs.value[row.id]})});await load()}catch(e){error.value=e.message}finally{busy.value=false}}
function name(id){return counterparties.value.find(c=>c.id===id)?.name||id}
function money(n){return new Intl.NumberFormat('fr-FR',{maximumFractionDigits:0}).format(n||0)}
onMounted(load)
</script>
<template>
  <main class="trading"><header class="flex items-center gap-4 mb-5"><BackLink fallback="/"/><div><h1 class="text-xl font-bold">Relations et exécutions</h1><p class="text-xs text-slate-400 mt-1">Documentation bilatérale, positions de notes et preuve de règlement.</p></div><button class="btn-secondary ml-auto" @click="load">Actualiser</button></header>
    <p v-if="error" class="p-3 mb-4 bg-red-950 text-red-200 rounded" role="alert">{{error}}</p>
    <div class="columns"><form class="card form" @submit.prevent="save"><h2>{{editing?'Modifier la relation':'Créer une relation'}}</h2><label>Contrepartie<select v-model="form.counterparty_id" class="input" required :disabled="!!editing"><option :value="null" disabled>Choisir</option><option v-for="c in counterparties" :key="c.id" :value="c.id">{{c.name}}</option></select></label><label>Référence<input v-model="form.reference" class="input" required minlength="3" :disabled="!!editing"/></label><label>État<select v-model="form.status" class="input"><option>PENDING</option><option>ACTIVE</option><option>SUSPENDED</option><option>EXPIRED</option></select></label><label>Date d’effet<input v-model="form.effective_date" type="date" required class="input"/></label><label>Expiration<input v-model="form.expiry_date" type="date" class="input"/></label><label>Devise<input v-model="form.currency" required maxlength="3" class="input"/></label><label>Documentation / accord signé<textarea v-model="form.documentation_reference" class="input" :required="form.status==='ACTIVE'" maxlength="1000"/></label><label>Limite brute (€)<input v-model.number="form.gross_notional_limit" type="number" min="1" required class="input"/></label><label class="check"><input v-model="form.note_distribution_allowed" type="checkbox"/> Autoriser les notes</label><label class="check"><input v-model="form.otc_allowed" type="checkbox"/> Autoriser l’OTC</label><template v-if="form.otc_allowed"><p class="text-xs text-slate-400">Les accords ISDA et CSA sont administrés dans <RouterLink to="/ccr" class="text-blue-400">Risque de contrepartie</RouterLink>. Une référence existante et active est exigée.</p><label>ID du master agreement<input v-model.number="form.master_agreement_id" type="number" min="1" required class="input"/></label><label class="check"><input v-model="form.csa_required" type="checkbox"/> CSA requis</label><label>ID du CSA<input v-model.number="form.csa_id" type="number" min="1" :required="form.csa_required" class="input"/></label></template><label>Règlement<select v-model="form.settlement" class="input"><option>DVP</option><option>FREE_OF_PAYMENT</option></select></label><label>Notes<textarea v-model="form.notes" class="input" maxlength="3000"/></label><button class="btn-primary" :disabled="busy">Enregistrer</button><button v-if="editing" type="button" class="btn-secondary" @click="reset">Annuler</button></form>
      <section class="space-y-5 min-w-0"><div class="card overflow-auto"><h2>Relations de mon entité</h2><table><thead><tr><th>Contrepartie / référence</th><th>État</th><th>Périmètre</th><th>Limite</th><th></th></tr></thead><tbody><tr v-for="r in relations" :key="r.id"><td>{{name(r.counterparty_id)}}<small>{{r.reference}} · v{{r.version}}</small></td><td>{{r.status}}<small>{{r.effective_date}}</small></td><td>{{r.note_distribution_allowed?'Notes':''}} {{r.otc_allowed?'OTC':''}}<small>{{r.csa_required?'CSA requis':''}}</small></td><td>{{money(r.gross_notional_limit)}} {{r.currency}}</td><td><button class="btn-secondary" @click="edit(r)">Modifier</button></td></tr><tr v-if="!relations.length"><td colspan="5">Aucune relation enregistrée.</td></tr></tbody></table></div>
      <div class="card overflow-auto"><h2>Journal des exécutions</h2><p class="text-xs text-slate-400 mb-3">BUY / SELL exprime le sens de notre entité. La preuve documente le règlement ; elle n’envoie aucun paiement bancaire. Le booking se fait dans <RouterLink to="/pricer" class="underline">Pricer → Deal</RouterLink>, avec l’option journal des relations.</p><table><thead><tr><th>Deal</th><th>Contrepartie / émetteur</th><th>Sens</th><th>Nominal / prix</th><th>Règlement</th></tr></thead><tbody><tr v-for="d in executions" :key="d.id"><td><RouterLink :to="'/booking?deal='+d.deal_id" class="text-blue-400">{{d.deal_reference}}</RouterLink><small>{{d.instrument_reference}}</small></td><td>{{d.counterparty}}<small>Émetteur : {{d.issuer}}</small></td><td>{{d.our_side}}</td><td>{{money(d.nominal)}} {{d.currency}}<small>{{d.price_traded}} %</small></td><td>{{d.settlement_status}}<small>Valeur {{d.value_date}}</small><form v-if="d.settlement_status==='PENDING'" @submit.prevent="settle(d)"><input v-model="proofs[d.id]" class="input mt-2" placeholder="Référence de la preuve" minlength="5" maxlength="200" required/><button class="btn-secondary mt-2" :disabled="busy">Confirmer le règlement</button></form><small v-else>{{d.settlement_reference}}</small></td></tr><tr v-if="!executions.length"><td colspan="5">Aucune note bookée avec une relation bilatérale.</td></tr></tbody></table></div>
      <div v-if="positions" class="card overflow-auto"><h2>Positions par instrument et émetteur</h2><p class="text-xs text-slate-400 mb-3">{{positions.risk_definition}} Un nominal négatif représente notamment les notes émises par notre entité.</p><table><thead><tr><th>Instrument</th><th>Émetteur</th><th>Nominal net</th><th>Cash restant à régler</th></tr></thead><tbody><tr v-for="p in positions.positions" :key="p.instrument_reference+p.issuer"><td>{{p.instrument_reference}}</td><td>{{p.issuer}}</td><td>{{money(p.nominal)}} {{p.currency}}</td><td>{{money(p.pending_cash)}} {{p.currency}}</td></tr></tbody></table></div></section>
    </div>
  </main>
</template>
<style scoped>
.trading{padding:24px;width:100%;max-width:1500px;margin:auto;color:var(--text)}.columns{display:grid;grid-template-columns:300px minmax(0,1fr);gap:20px}.form{display:flex;flex-direction:column;gap:12px;align-self:start}.form label{display:flex;flex-direction:column;font-size:12px;gap:5px}.form .check{flex-direction:row;align-items:center}h2{font-weight:700;font-size:16px;margin-bottom:12px}table{width:100%;font-size:12px}th,td{text-align:left;padding:12px 8px;border-bottom:1px solid var(--border);vertical-align:top}td small{display:block;color:var(--subtle);font-size:11px;margin-top:5px}.input{width:100%}@media(max-width:850px){.columns{grid-template-columns:1fr}.trading{padding:12px}}
</style>
